/*
Deployment script for iercapstone

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "iercapstone"
:setvar DefaultFilePrefix "iercapstone"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [master];


GO

IF (DB_ID(N'$(DatabaseName)') IS NOT NULL) 
BEGIN
    ALTER DATABASE [$(DatabaseName)]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [$(DatabaseName)];
END

GO
PRINT N'Creating $(DatabaseName)...'
GO
CREATE DATABASE [$(DatabaseName)]
    ON 
    PRIMARY(NAME = [$(DatabaseName)], FILENAME = N'$(DefaultDataPath)$(DefaultFilePrefix)_Primary.mdf')
    LOG ON (NAME = [$(DatabaseName)_log], FILENAME = N'$(DefaultLogPath)$(DefaultFilePrefix)_Primary.ldf') COLLATE SQL_Latin1_General_CP1_CI_AS
GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ANSI_NULLS ON,
                ANSI_PADDING ON,
                ANSI_WARNINGS ON,
                ARITHABORT ON,
                CONCAT_NULL_YIELDS_NULL ON,
                NUMERIC_ROUNDABORT OFF,
                QUOTED_IDENTIFIER ON,
                ANSI_NULL_DEFAULT ON,
                CURSOR_DEFAULT LOCAL,
                RECOVERY FULL,
                CURSOR_CLOSE_ON_COMMIT OFF,
                AUTO_CREATE_STATISTICS ON,
                AUTO_SHRINK OFF,
                AUTO_UPDATE_STATISTICS ON,
                RECURSIVE_TRIGGERS OFF 
            WITH ROLLBACK IMMEDIATE;
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_CLOSE OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ALLOW_SNAPSHOT_ISOLATION OFF;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET READ_COMMITTED_SNAPSHOT OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_UPDATE_STATISTICS_ASYNC OFF,
                PAGE_VERIFY NONE,
                DATE_CORRELATION_OPTIMIZATION OFF,
                DISABLE_BROKER,
                PARAMETERIZATION SIMPLE,
                SUPPLEMENTAL_LOGGING OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF IS_SRVROLEMEMBER(N'sysadmin') = 1
    BEGIN
        IF EXISTS (SELECT 1
                   FROM   [master].[dbo].[sysdatabases]
                   WHERE  [name] = N'$(DatabaseName)')
            BEGIN
                EXECUTE sp_executesql N'ALTER DATABASE [$(DatabaseName)]
    SET TRUSTWORTHY OFF,
        DB_CHAINING OFF 
    WITH ROLLBACK IMMEDIATE';
            END
    END
ELSE
    BEGIN
        PRINT N'The database settings cannot be modified. You must be a SysAdmin to apply these settings.';
    END


GO
IF IS_SRVROLEMEMBER(N'sysadmin') = 1
    BEGIN
        IF EXISTS (SELECT 1
                   FROM   [master].[dbo].[sysdatabases]
                   WHERE  [name] = N'$(DatabaseName)')
            BEGIN
                EXECUTE sp_executesql N'ALTER DATABASE [$(DatabaseName)]
    SET HONOR_BROKER_PRIORITY OFF 
    WITH ROLLBACK IMMEDIATE';
            END
    END
ELSE
    BEGIN
        PRINT N'The database settings cannot be modified. You must be a SysAdmin to apply these settings.';
    END


GO
ALTER DATABASE [$(DatabaseName)]
    SET TARGET_RECOVERY_TIME = 0 SECONDS 
    WITH ROLLBACK IMMEDIATE;


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET FILESTREAM(NON_TRANSACTED_ACCESS = OFF),
                CONTAINMENT = NONE 
            WITH ROLLBACK IMMEDIATE;
    END


GO
USE [$(DatabaseName)];


GO
IF fulltextserviceproperty(N'IsFulltextInstalled') = 1
    EXECUTE sp_fulltext_database 'enable';


GO
PRINT N'Creating [dbo].[__MigrationHistory]...';


GO
CREATE TABLE [dbo].[__MigrationHistory] (
    [MigrationId]    NVARCHAR (150)  NOT NULL,
    [ContextKey]     NVARCHAR (300)  NOT NULL,
    [Model]          VARBINARY (MAX) NOT NULL,
    [ProductVersion] NVARCHAR (32)   NOT NULL,
    CONSTRAINT [PK_dbo.__MigrationHistory] PRIMARY KEY CLUSTERED ([MigrationId] ASC, [ContextKey] ASC)
);


GO
PRINT N'Creating [dbo].[CacSoChuyenMaus]...';


GO
CREATE TABLE [dbo].[CacSoChuyenMaus] (
    [Id]   INT IDENTITY (1, 1) NOT NULL,
    [Year] INT NOT NULL,
    CONSTRAINT [PK_dbo.CacSoChuyenMaus] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[CacSoNhanMaus]...';


GO
CREATE TABLE [dbo].[CacSoNhanMaus] (
    [Id]   INT IDENTITY (1, 1) NOT NULL,
    [Year] INT NOT NULL,
    CONSTRAINT [PK_dbo.CacSoNhanMaus] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ChiTieuPhanTiches]...';


GO
CREATE TABLE [dbo].[ChiTieuPhanTiches] (
    [Id]          INT             IDENTITY (1, 1) NOT NULL,
    [TenChiTieu]  NVARCHAR (MAX)  NULL,
    [ChiPhi]      DECIMAL (18, 2) NOT NULL,
    [NhomChiTieu] NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_dbo.ChiTieuPhanTiches] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[FormKQs]...';


GO
CREATE TABLE [dbo].[FormKQs] (
    [Id]          INT            IDENTITY (1, 1) NOT NULL,
    [NoiLayMau]   NVARCHAR (MAX) NULL,
    [NgayGuiMau]  DATETIME       NOT NULL,
    [DiaChi]      NVARCHAR (MAX) NULL,
    [LoaiMau]     NVARCHAR (MAX) NULL,
    [ViTriLayMau] NVARCHAR (MAX) NULL,
    [MaMau]       NVARCHAR (MAX) NULL,
    [MaDon]       NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_dbo.FormKQs] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[KetQuaPhanTichFormKQs]...';


GO
CREATE TABLE [dbo].[KetQuaPhanTichFormKQs] (
    [Id]                 INT            IDENTITY (1, 1) NOT NULL,
    [ChiTieu]            NVARCHAR (MAX) NULL,
    [DonVi]              NVARCHAR (MAX) NULL,
    [GiaTri]             INT            NOT NULL,
    [PhuongPhapPhanTich] NVARCHAR (MAX) NULL,
    [FormKQ_Id]          INT            NULL,
    CONSTRAINT [PK_dbo.KetQuaPhanTichFormKQs] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[KetQuaPhanTichFormKQs].[IX_FormKQ_Id]...';


GO
CREATE NONCLUSTERED INDEX [IX_FormKQ_Id]
    ON [dbo].[KetQuaPhanTichFormKQs]([FormKQ_Id] ASC);


GO
PRINT N'Creating [dbo].[KQThuNghiemMaus]...';


GO
CREATE TABLE [dbo].[KQThuNghiemMaus] (
    [Id]                INT            IDENTITY (1, 1) NOT NULL,
    [ChiTieuThuNghiem]  NVARCHAR (MAX) NULL,
    [DonVi]             NVARCHAR (MAX) NULL,
    [KetQua]            NVARCHAR (MAX) NULL,
    [NguoiThucHien]     NVARCHAR (MAX) NULL,
    [SoKQThuNghiems_Id] INT            NULL,
    CONSTRAINT [PK_dbo.KQThuNghiemMaus] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[KQThuNghiemMaus].[IX_SoKQThuNghiems_Id]...';


GO
CREATE NONCLUSTERED INDEX [IX_SoKQThuNghiems_Id]
    ON [dbo].[KQThuNghiemMaus]([SoKQThuNghiems_Id] ASC);


GO
PRINT N'Creating [dbo].[MauLayHienTruongs]...';


GO
CREATE TABLE [dbo].[MauLayHienTruongs] (
    [Id]                 INT            IDENTITY (1, 1) NOT NULL,
    [MaMau]              NVARCHAR (MAX) NULL,
    [MaMauKH]            NVARCHAR (MAX) NULL,
    [ViTriLayMau]        NVARCHAR (MAX) NULL,
    [SoLuong]            INT            NOT NULL,
    [DonVi]              NVARCHAR (MAX) NULL,
    [MoTaMau]            NVARCHAR (MAX) NULL,
    [NgayNhanMau]        DATETIME       NOT NULL,
    [NgayTraMau]         DATETIME       NOT NULL,
    [MaHDPhanTich]       INT            NOT NULL,
    [MaChiTieuPhanTich]  NVARCHAR (MAX) NULL,
    [NamLayMau]          INT            NOT NULL,
    [ChiTieuPhanTich_Id] INT            NULL,
    [PhieuYeuCau_Id]     INT            NULL,
    CONSTRAINT [PK_dbo.MauLayHienTruongs] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[MauLayHienTruongs].[IX_ChiTieuPhanTich_Id]...';


GO
CREATE NONCLUSTERED INDEX [IX_ChiTieuPhanTich_Id]
    ON [dbo].[MauLayHienTruongs]([ChiTieuPhanTich_Id] ASC);


GO
PRINT N'Creating [dbo].[MauLayHienTruongs].[IX_PhieuYeuCau_Id]...';


GO
CREATE NONCLUSTERED INDEX [IX_PhieuYeuCau_Id]
    ON [dbo].[MauLayHienTruongs]([PhieuYeuCau_Id] ASC);


GO
PRINT N'Creating [dbo].[PhieuYeuCaus]...';


GO
CREATE TABLE [dbo].[PhieuYeuCaus] (
    [Id]               INT            IDENTITY (1, 1) NOT NULL,
    [MaDon]            NVARCHAR (MAX) NULL,
    [TenKhachHang]     NVARCHAR (MAX) NULL,
    [TenDaiDien]       NVARCHAR (MAX) NULL,
    [DiaChiLayMau]     NVARCHAR (MAX) NULL,
    [DiaChiKhachHang]  NVARCHAR (MAX) NULL,
    [MaSoThue]         NVARCHAR (MAX) NULL,
    [SoDienThoai]      NVARCHAR (MAX) NULL,
    [SoFax]            NVARCHAR (MAX) NULL,
    [NgayTaoHD]        DATETIME       NOT NULL,
    [NgayDuKienTraMau] DATETIME       NOT NULL,
    [NamLayHD]         INT            NOT NULL,
    CONSTRAINT [PK_dbo.PhieuYeuCaus] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[RoleMasters]...';


GO
CREATE TABLE [dbo].[RoleMasters] (
    [Id]       INT            IDENTITY (1, 1) NOT NULL,
    [RoleName] NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_dbo.RoleMasters] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[SoChuyenMaus]...';


GO
CREATE TABLE [dbo].[SoChuyenMaus] (
    [Id]                INT            IDENTITY (1, 1) NOT NULL,
    [MaKhachHang]       NVARCHAR (MAX) NULL,
    [MaMau]             NVARCHAR (MAX) NULL,
    [ChiTieuThuNghiem]  NVARCHAR (MAX) NULL,
    [NguoiGiaoMau]      NVARCHAR (MAX) NULL,
    [NguoiNhanMau]      NVARCHAR (MAX) NULL,
    [NgayGiaoMau]       DATETIME       NOT NULL,
    [NgayTraKetQua]     DATETIME       NOT NULL,
    [DienTen]           NVARCHAR (MAX) NULL,
    [GhiChu]            NVARCHAR (MAX) NULL,
    [CacSoChuyenMau_Id] INT            NULL,
    CONSTRAINT [PK_dbo.SoChuyenMaus] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[SoChuyenMaus].[IX_CacSoChuyenMau_Id]...';


GO
CREATE NONCLUSTERED INDEX [IX_CacSoChuyenMau_Id]
    ON [dbo].[SoChuyenMaus]([CacSoChuyenMau_Id] ASC);


GO
PRINT N'Creating [dbo].[SoKQThuNghiems]...';


GO
CREATE TABLE [dbo].[SoKQThuNghiems] (
    [Id]          INT            IDENTITY (1, 1) NOT NULL,
    [KyHieuMau]   NVARCHAR (MAX) NULL,
    [NgayNhanMau] NVARCHAR (MAX) NULL,
    [NgayTraMau]  NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_dbo.SoKQThuNghiems] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[SoNhanMaus]...';


GO
CREATE TABLE [dbo].[SoNhanMaus] (
    [Id]                 INT            IDENTITY (1, 1) NOT NULL,
    [PhieuYeuCau]        NVARCHAR (MAX) NULL,
    [TenDiaChiKhachHang] NVARCHAR (MAX) NULL,
    [MaSo]               NVARCHAR (MAX) NULL,
    [ChiTieuThuNghiem]   NVARCHAR (MAX) NULL,
    [NgayNhan]           DATETIME       NOT NULL,
    [NgayTraKetQua]      DATETIME       NOT NULL,
    [KHKyNhanTraTien]    BIT            NOT NULL,
    [KHKyNhanTraKQ]      BIT            NOT NULL,
    [MaMauKH]            NVARCHAR (MAX) NULL,
    [CacSoNhanMau_Id]    INT            NULL,
    CONSTRAINT [PK_dbo.SoNhanMaus] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[SoNhanMaus].[IX_CacSoNhanMau_Id]...';


GO
CREATE NONCLUSTERED INDEX [IX_CacSoNhanMau_Id]
    ON [dbo].[SoNhanMaus]([CacSoNhanMau_Id] ASC);


GO
PRINT N'Creating [dbo].[Users]...';


GO
CREATE TABLE [dbo].[Users] (
    [Id]       INT            IDENTITY (1, 1) NOT NULL,
    [username] NVARCHAR (MAX) NULL,
    [password] NVARCHAR (MAX) NULL,
    [fullname] NVARCHAR (MAX) NULL,
    [roleId]   INT            NOT NULL,
    CONSTRAINT [PK_dbo.Users] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[FK_dbo.KetQuaPhanTichFormKQs_dbo.FormKQs_FormKQ_Id]...';


GO
ALTER TABLE [dbo].[KetQuaPhanTichFormKQs]
    ADD CONSTRAINT [FK_dbo.KetQuaPhanTichFormKQs_dbo.FormKQs_FormKQ_Id] FOREIGN KEY ([FormKQ_Id]) REFERENCES [dbo].[FormKQs] ([Id]);


GO
PRINT N'Creating [dbo].[FK_dbo.KQThuNghiemMaus_dbo.SoKQThuNghiems_SoKQThuNghiems_Id]...';


GO
ALTER TABLE [dbo].[KQThuNghiemMaus]
    ADD CONSTRAINT [FK_dbo.KQThuNghiemMaus_dbo.SoKQThuNghiems_SoKQThuNghiems_Id] FOREIGN KEY ([SoKQThuNghiems_Id]) REFERENCES [dbo].[SoKQThuNghiems] ([Id]);


GO
PRINT N'Creating [dbo].[FK_dbo.MauLayHienTruongs_dbo.ChiTieuPhanTiches_ChiTieuPhanTich_Id]...';


GO
ALTER TABLE [dbo].[MauLayHienTruongs]
    ADD CONSTRAINT [FK_dbo.MauLayHienTruongs_dbo.ChiTieuPhanTiches_ChiTieuPhanTich_Id] FOREIGN KEY ([ChiTieuPhanTich_Id]) REFERENCES [dbo].[ChiTieuPhanTiches] ([Id]);


GO
PRINT N'Creating [dbo].[FK_dbo.MauLayHienTruongs_dbo.PhieuYeuCaus_PhieuYeuCau_Id]...';


GO
ALTER TABLE [dbo].[MauLayHienTruongs]
    ADD CONSTRAINT [FK_dbo.MauLayHienTruongs_dbo.PhieuYeuCaus_PhieuYeuCau_Id] FOREIGN KEY ([PhieuYeuCau_Id]) REFERENCES [dbo].[PhieuYeuCaus] ([Id]);


GO
PRINT N'Creating [dbo].[FK_dbo.SoChuyenMaus_dbo.CacSoChuyenMaus_CacSoChuyenMau_Id]...';


GO
ALTER TABLE [dbo].[SoChuyenMaus]
    ADD CONSTRAINT [FK_dbo.SoChuyenMaus_dbo.CacSoChuyenMaus_CacSoChuyenMau_Id] FOREIGN KEY ([CacSoChuyenMau_Id]) REFERENCES [dbo].[CacSoChuyenMaus] ([Id]);


GO
PRINT N'Creating [dbo].[FK_dbo.SoNhanMaus_dbo.CacSoNhanMaus_CacSoNhanMau_Id]...';


GO
ALTER TABLE [dbo].[SoNhanMaus]
    ADD CONSTRAINT [FK_dbo.SoNhanMaus_dbo.CacSoNhanMaus_CacSoNhanMau_Id] FOREIGN KEY ([CacSoNhanMau_Id]) REFERENCES [dbo].[CacSoNhanMaus] ([Id]);


GO
DECLARE @VarDecimalSupported AS BIT;

SELECT @VarDecimalSupported = 0;

IF ((ServerProperty(N'EngineEdition') = 3)
    AND (((@@microsoftversion / power(2, 24) = 9)
          AND (@@microsoftversion & 0xffff >= 3024))
         OR ((@@microsoftversion / power(2, 24) = 10)
             AND (@@microsoftversion & 0xffff >= 1600))))
    SELECT @VarDecimalSupported = 1;

IF (@VarDecimalSupported > 0)
    BEGIN
        EXECUTE sp_db_vardecimal_storage_format N'$(DatabaseName)', 'ON';
    END


GO
PRINT N'Update complete.';


GO
