//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IERSystem.Areas.Administrator.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IERSystemModelContainer : DbContext
    {
        public IERSystemModelContainer()
            : base("name=IERSystemModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PhieuYeuCau> PhieuYeuCaus { get; set; }
        public virtual DbSet<MauLayHienTruong> MauLayHienTruongs { get; set; }
        public virtual DbSet<ChiTieuPhanTich> ChiTieuPhanTiches { get; set; }
        public virtual DbSet<SoNhanMau> SoNhanMaus { get; set; }
        public virtual DbSet<CacSoNhanMau> CacSoNhanMaus { get; set; }
        public virtual DbSet<SoChuyenMau> SoChuyenMaus { get; set; }
        public virtual DbSet<CacSoChuyenMau> CacSoChuyenMaus { get; set; }
        public virtual DbSet<KQThuNghiemMau> KQThuNghiemMaus { get; set; }
        public virtual DbSet<SoKQThuNghiem> SoKQThuNghiems { get; set; }
        public virtual DbSet<FormKQ> FormKQs { get; set; }
        public virtual DbSet<NhomChiTieu> NhomChiTieux { get; set; }
    }
}
