//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IERSystem.Areas.Administrator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KQPhanTichFormKQ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KQPhanTichFormKQ()
        {
            this.PhuongPhapPhanTiches = new HashSet<PhuongPhapPhanTich>();
        }
    
        public long Id { get; set; }
        public string DonVi { get; set; }
        public string GiaTri { get; set; }
        public long FormKQId { get; set; }
    
        public virtual FormKQ FormKQ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhuongPhapPhanTich> PhuongPhapPhanTiches { get; set; }
    }
}
