//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IERSystem.Areas.Administrator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MauLayHienTruong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MauLayHienTruong()
        {
            this.ChiTieuPhanTiches = new HashSet<ChiTieuPhanTich>();
        }
    
        public long Id { get; set; }
        public string MaMau { get; set; }
        public string MaMauKH { get; set; }
        public string DonVi { get; set; }
        public string MoTaMau { get; set; }
        public int SoLuong { get; set; }
        public string ViTriLayMau { get; set; }
        public long PhieuYeuCauId { get; set; }
    
        public virtual PhieuYeuCau PhieuYeuCau { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTieuPhanTich> ChiTieuPhanTiches { get; set; }
        public virtual SoNhanMau SoNhanMau { get; set; }
        public virtual SoChuyenMau SoChuyenMau { get; set; }
        public virtual SoKQThuNghiem SoKQThuNghiem { get; set; }
    }
}
