
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IERSystem.Areas.Administrator.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PhuongPhapPhanTich
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PhuongPhapPhanTich()
    {

        this.KQPhanTichFormKQs = new HashSet<KQPhanTichFormKQ>();

    }


    public long Id { get; set; }

    public string TenPhuongPhap { get; set; }

    public long ChiTieuPhanTichId { get; set; }



    public virtual ChiTieuPhanTich ChiTieuPhanTich { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<KQPhanTichFormKQ> KQPhanTichFormKQs { get; set; }

}

}
