//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IERSystem.Areas.Administrator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoChuyenMau
    {
        public long Id { get; set; }
        public string DienTen { get; set; }
        public string GhiChu { get; set; }
        public System.DateTime NgayGiaoMau { get; set; }
        public System.DateTime NgayTraKQ { get; set; }
        public long CacSoChuyenMauId { get; set; }
        public int UserId { get; set; }
    
        public virtual CacSoChuyenMau CacSoChuyenMau { get; set; }
        public virtual MauLayHienTruong MauLayHienTruong { get; set; }
        public virtual User CreatedBy { get; set; }
    }
}
